### PR TITLE
Fix description of SEGV issue in HISTORY

### PR DESCRIPTION
**Pull request by carsonip**
I looked into the related issues and think that the description is quite misleading or may be wrong.

### CODE REVIEW

**Comment by methane** [comment]
Only rollback is affected?

**Comment by carsonip** [comment]
I checked the v1.3.13 code, there was no checking for `rollback()` and `commit()`. Not sure whether it will cause SEGV tho. https://github.com/PyMySQL/mysqlclient-python/commit/4a4978d6b10e6bc7983ad41f92277a635133f80f#diff-b86fdc88461d69279e84018bca8ea267R879

**Comment by methane** [comment]
What did you confirmed?
I get report only for close().  I added checks for many functions, not only close() and rollback().

**Comment by carsonip** [comment]
I would say it at least affects `rollback()` according to #270. But I'll reproduce the segfault later today and see what functions are exactly affected.

**Comment by methane** [comment]
I changed the history entry to not refer to actual method name causing SEGV.

**Comment by carsonip** [comment]
The description looks better now. Thanks!

**Pull request merged**
