### PR TITLE
adding requirement for Mac OS

### PR DESCRIPTION
**Pull request by ardinusawan**
Im trying this in my mac, and work! 
Hope this help

### CODE REVIEW

**Comment by methane** [comment]
thanks

**Comment by zyong9891** [comment]
Is there any problem with my virtualenv? I have a problem installing mysqlclient
image

madOS Sierra 10.12.4
anybody help me? Thanks very much!!

**Comment by methane** [comment]
Why don't you search issues before asking question?
Read very recent closed issue.

2017/05/16 午後4:04 "AnteeRun" <notifications@github.com>:

**Comment by zyong9891** [comment]
@methane 
Thank you very much! (found this issue through Search Engine. )
I found solution in  issue #169 . Sorry for bothering you.

brief solution for later-comers:
i) modify file:  /usr/local/bin/mysql_config (which mysql_config) 
   origin:
`# Create options
libs="-L$pkglibdir"
libs="$libs -l "`
modified to
`# Create options 
libs="-L$pkglibdir"
libs="$libs -lmysqlclient -lssl -lcrypto"
`
ii)add environment veriables(brew info openssl)
 `export LDFLAGS="-L/usr/local/opt/openssl/lib"`
`export CPPFLAGS="-I/usr/local/opt/openssl/include"`
iii)pip install mysqlclient
 successed!

thank you.

**Comment by reach009** [comment]
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/5v/whz01gcs29518gly2s1k76t80000gn/T/pip-install-n4seovbq/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5v/whz01gcs29518gly2s1k76t80000gn/T/pip-record-20soowiu/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/5v/whz01gcs29518gly2s1k76t80000gn/T/pip-install-n4seovbq/mysqlclient/

**Comment by reach009** [comment]
@PaleoWoods : I tried your method, but it gives me this error.

`Collecting mysqlclient
  Using cached https://files.pythonhosted.org/packages/73/79/67ddf24ac31b05d741f0ac87fa612c7a11bab1b39b8270ed7344d149f8af/mysqlclient-1.4.2.tar.gz
Installing collected packages: mysqlclient
  Running setup.py install for mysqlclient ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/5v/whz01gcs29518gly2s1k76t80000gn/T/pip-install-n4seovbq/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5v/whz01gcs29518gly2s1k76t80000gn/T/pip-record-20soowiu/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    copying MySQLdb/_exceptions.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    copying MySQLdb/compat.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    copying MySQLdb/connections.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    copying MySQLdb/converters.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    copying MySQLdb/release.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    copying MySQLdb/times.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb
    creating build/lib.macosx-10.9-x86_64-3.7/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.macosx-10.9-x86_64-3.7/MySQLdb/constants
    running build_ext
    building 'MySQLdb._mysql' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/MySQLdb
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -Dversion_info=(1,4,2,'final',0) -D__version__=1.4.2 -I/usr/local/Cellar/mysql/8.0.15/include/mysql -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c MySQLdb/_mysql.c -o build/temp.macosx-10.9-x86_64-3.7/MySQLdb/_mysql.o
    gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.7/MySQLdb/_mysql.o -L/usr/local/Cellar/mysql/8.0.15/lib -lmysqlclient -lssl -lcrypto -o build/lib.macosx-10.9-x86_64-3.7/MySQLdb/_mysql.cpython-37m-darwin.so
    ld: library not found for -lssl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/5v/whz01gcs29518gly2s1k76t80000gn/T/pip-install-n4seovbq/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5v/whz01gcs29518gly2s1k76t80000gn/T/pip-record-20soowiu/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/5v/whz01gcs29518gly2s1k76t80000gn/T/pip-install-n4seovbq/mysqlclient/`

**Pull request merged**
