### PR TITLE
Handle mariadb static library called mariadbclient.a

### LINKED ISSUE #261: Problem building from source against MariaDB 10.2.11
I am building mysqlclient 1.3.13 from source against Python 3.6.3 and MariaDB 10.2.11.

It fails to build with an error about libNone.a.

I tracked this down to `client` not being set properly in `setup_posix.py`

Here's a patch which fixes it. If you'd prefer this as a PR then I'm happy to make one, but I wanted to check that I wasn't doing anything silly first...
```
--- setup_posix.py.orig 2018-06-27 12:17:09.000000000 +0100
+++ setup_posix.py      2018-08-29 15:15:21.941166016 +0100
@@ -75,13 +75,18 @@
 
     # properly handle mysql client libraries that are not called libmysqlclient
     client = None
-    CLIENT_LIST = ['mysqlclient', 'mysqlclient_r', 'mysqld',
+    CLIENT_LIST = ['mysqlclient', 'mysqlclient_r', 'mysqld', 'mariadb',
                    'perconaserverclient', 'perconaserverclient_r']
     for c in CLIENT_LIST:
         if c in libraries:
             client = c
             break
 
+    if client == 'mariadb':
+        client = 'mariadbclient'
+    if client is None:
+        raise ValueError("Couldn't identify mysql client library")
+
     if static:
         extra_objects.append(os.path.join(library_dirs[0], 'lib%s.a' % client))
         if client in libraries:

```

### PR DESCRIPTION
**Pull request by edmondac**
Fixes #261 

Built with:
Python 3.6.3
MariaDB 10.2.11
python setup.py build --static

### CODE REVIEW

**Comment by methane** [comment]
Please paste output of `mysql_config` (or `mariadb_config`).

**Comment by methane** [comment]
I think `-lmariadb` should be used when without `--static` option.

**Comment by edmondac** [comment]
```
$ mysql_config
Usage: <path-removed>MariaDB/10.2.11-iomkl-2018a/bin/mysql_config [OPTIONS]
Options:
        --cflags         [-I<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql -I<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql/mysql]
        --include        [-I<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql -I<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql/mysql]
        --libs           [-L<path-removed>MariaDB/10.2.11-iomkl-2018a/lib/ -lmariadb -lnsl -lz -ldl -lm -lpthread -lssl -lcrypto]
        --libs_r         [-L<path-removed>MariaDB/10.2.11-iomkl-2018a/lib/ -lmariadb -lnsl -lz -ldl -lm -lpthread -lssl -lcrypto]
        --plugindir      [<path-removed>MariaDB/10.2.11-iomkl-2018a/lib/plugin]
        --socket         [/tmp/mysql.sock]
        --port           [3306]
        --version        [10.2.11]
        --libmysqld-libs [-L<path-removed>MariaDB/10.2.11-iomkl-2018a/lib  -lmysqld -lpthread -lz -lssl -lcrypto -lcrypt -llzma -lbz2 -lnuma -lsystemd]
        --variable=VAR   VAR is one of:
                pkgincludedir [<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql]
                pkglibdir     [<path-removed>MariaDB/10.2.11-iomkl-2018a/lib]
                plugindir     [<path-removed>MariaDB/10.2.11-iomkl-2018a/lib/plugin]


$ mariadb_config 
Copyright 2011-2015 MariaDB Corporation AB
Get compiler flags for using the MariaDB Connector/C.
Usage: mariadb_config [OPTIONS]
  --cflags        [-I<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql -I<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql/mysql]
  --include       [-I<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql -I<path-removed>MariaDB/10.2.11-iomkl-2018a/include/mysql/mysql]
  --libs          [-L<path-removed>MariaDB/10.2.11-iomkl-2018a/lib/ -lmariadb -lnsl -lz -ldl -lm -lpthread -lssl -lcrypto]
  --libs_r        [-L<path-removed>MariaDB/10.2.11-iomkl-2018a/lib/ -lmariadb -lnsl -lz -ldl -lm -lpthread -lssl -lcrypto]
  --libs_sys      [-lnsl -lz -ldl -lm -lpthread -lssl -lcrypto]
  --version       [10.2.11]
  --cc_version    [3.0.2]
  --socket        [/tmp/mysql.sock]
  --port          [3306]
  --plugindir     [<path-removed>MariaDB/10.2.11-iomkl-2018a/lib/plugin]
  --tlsinfo       [OpenSSL 1.0.2k]

```

**Comment by edmondac** [comment]
Do I need to do anything else with this now?

**Pull request merged**
