### PR TITLE
Remove context interface from Connector

### PR DESCRIPTION
**Pull request by methane**

### CODE REVIEW

**Comment by antimirov** [comment]
Guys, sorry for writing into this closed ticket, but what was the reasoning behind the removal of such an important functionality?

**Comment by methane** [comment]
What do you expect the context interface do?
Do you read the code?  The removed code did what you expected?

**Comment by antimirov** [comment]
Short background: I've always used Postgresql, mostly with psycopg2, which has similar contextmanager functionality.

My confusion was that while in this pull request https://github.com/PyMySQL/mysqlclient-python/pull/295 (Dec 2018) you deleted __enter__ and __exit__ methods of the connection, in the recent PR https://github.com/PyMySQL/mysqlclient-python/pull/413 it's back again, albeit in a much shorter form. That's why I was confused, what was the reason to remove it and why is it now okay to put it back?

**Comment by methane** [comment]
What do you expect the context interface do?
Do you read the code? The removed code did what you expected?

**Comment by antimirov** [comment]
From what I can see the old code was quite useful - it provided a contextmanager which was creating a cursor instance, plus doing a commit or rollback in exit.

To answer your questions: This is what I would expect from such a ctx manager. Yes, I read the code. Yes, it seems like it did what I expected.

**Comment by methane** [comment]
Hm, it seems psycopg2 behavior is the same to old `__exit__` in mysqlclient.
But it didn't many users expects.  Many people want `__exit__` close the connection.

* https://github.com/PyMySQL/PyMySQL/issues/248
* https://github.com/PyMySQL/PyMySQL/issues/446
* https://github.com/PyMySQL/PyMySQL/issues/396
* https://github.com/PyMySQL/PyMySQL/issues/735
* Airflow has connection leaks because they expect `__exit__` close the connection. https://github.com/apache/airflow/blob/7bebe8ddbc69ed5a1b316d31a2aa542f6bc60432/tests/operators/test_operators.py#L370-L371

That's why I change the behavior of the `__exit__`.

And I removed the `__exit__` once and add it again with different behavior because I want to notice every user.  Many users don't care about DeprecationWarning.

**Comment by antimirov** [comment]
I agree, with some of the comments in your links that I would like a contextmanager of a connection to returns a connection, and for cursor return a cursor, not to combine these things in one entity. So I can have extra control when I want to apply .commit() manually, for example.

**Comment by kate-shine** [comment]
While I agree that your changes make sense, you are making the behavior of mysqlclient-python inconsistent with not only psycopg2, but with the standard library sqlite3 as well.

https://docs.python.org/3.8/library/sqlite3.html#using-the-connection-as-a-context-manager

Some people probably expected a different behavior, but are you sure that there aren't more of them who expect it to behave the way the rest of the world does?

**Pull request merged**
