### PR TITLE
Use _binary prefix for bytes/bytearray parameters (now optional)

### PR DESCRIPTION
**Pull request by vtermanis**
This should hopefully address the problems of the previous attempt (#106, #123). An optional connection parameter is used to enable the behaviour. I've also added a unit test to check expected query parameter handling.

### CODE REVIEW

**Comment by methane** [comment]
thanks

**Comment by jkrukoff** [comment]
Excited to see this merged, my logs have been full of the spurious "invalid utf8" mysql warning since I switched to storing binary UUIDs due to this.

**Comment by pawl** [comment]
@methane do you plan to cut a release for this change soon?

**Comment by methane** [comment]
It seems Oracle start releasing MySQL Connector/C 6.1.9 with vs14 support.
https://dev.mysql.com/downloads/connector/c/

Currently, only win32 zip is upload.
Since I don't want to use MSI installer, I hope winx64 zip will be released soon.
This week is good timing to cut new release.

**Comment by methane** [comment]
I released mysqlclient 1.4.10 with Python 3.5 & 3.6 * 32bit & 64bit on Windows.
OTOH, Python 2.7 wheel is not built anymore.  Oracle stopped shipping vc9 and vc10 libs.
It's time to drop Python 2.7 support on Windows.

**Pull request merged**
